export const PORTFOLIO = [
  {
    id: '1',
    img: '/img/project_1.png',
    alt: 'project 1',
    link: 'https://startup-gitpage.vercel.app/profile/gaearon',
    description: 'Lorem ipsum, quis occaec',
  },
  {
    id: '2',
    img: '/img/project_2.png',
    alt: 'project 2',
    link: 'https://exchange-rate-ksbpoexgy-feralwater.vercel.app/',
    description: 'Lorem ipsum, quis occaec',
  },
  {
    id: '3',
    img: '/img/project_3.png',
    alt: 'project 3',
    link: 'https://posts-board-application.vercel.app/',
    description: 'Lorem ipsum, quis occaec',
  },
  {
    id: '4',
    img: '/img/project_4.png',
    alt: 'project 4',
    link: 'https://feralwater.github.io/Lemon/',
    description: 'Lorem ipsum, quis occaec',
  },
  {
    id: '5',
    img: '/img/project_5.png',
    alt: 'project 5',
    link: 'https://feralwater.github.io/Sloohi-bar/',
    description: 'Lorem ipsum, quis occaec',
  },
  {
    id: '6',
    img: '/img/project_6.png',
    alt: 'project 6',
    link: 'https://user-table.vercel.app/1',
    description: 'Lorem ipsum, quis occaec',
  },
  {
    id: '7',
    img: '/img/project_7.png',
    alt: 'project 7',
    link: 'https://scandiweb-test-task-git-main-feralwater.vercel.app/',
    description: 'Lorem ipsum, quis occaec',
  },
  {
    id: '8',
    img: '/img/project_8.png',
    alt: 'project 8',
    link: 'https://solid-octo-doodle-zeta.vercel.app/',
    description: 'English learning app, now in progress, August 2022',
  },
];
